version: "3.6"

services:
  login-service:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: login_service
    hostname: login_service
    ports:
      - "8083:80"
    networks:
      - default
  job-services:
    build:
      context: server
      dockerfile: Services/Dockerfile
    container_name: job_services
    hostname: job_services
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8082:80"
    volumes:
      - ./images_data:/workspace/images
    networks:
      - default
  inference-engine:
    image: capx-object:latest # do not change, leave as it is
    container_name: inference-engine
    hostname: inference-engine
    environment:
      - ROOT_LOGLEVEL=WARNING # logging level can be "DEBUG", "INFO", "WARNING"
      - BASEWORKER_LOGLEVEL=WARNING # logging level can be "DEBUG", "INFO", "WARNING"
      - HANDLER_LOGLEVEL=INFO # logging level can be "DEBUG", "INFO", "WARNING"
      - SERVER_BIND_INTERFACE=0.0.0.0 # default to accept from all IP
      - SERVER_PORT=80 # default to accept requests on port 80
      - SERVER_ENDPOINT=receive # default URL endpoint to receive request
      - CAPX_WORKER_NAME=object # do not change, leave as it is
      - CAPX_FORCE_CPU=true # or false
      - DARKNET_PATH=/workspace/src/module_object # do not change, leave as it is
    ports:
      - "8081:80" # 8081 is the host's port, 80 is the docker container's port (as above)
    volumes:
      - ./__logs:/workspace/logs # folder to save logs as optionally debug inputs & outputs
      - ./images_data:/workspace/images # folder to pass images to container
    restart: unless-stopped
    networks:
      - default
networks:
  default:
    name: app-net

#volumes:
#  images_data:
